# Sample Prometheus config

global:
  scrape_interval:     1s # Set the scrape interval to every 1 second. Default is every 1 minute.
  evaluation_interval: 1s # Evaluate rules every 1 second. The default is every 1 minute.

scrape_configs:
  - job_name: 'spring boot scrape'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['web-app:8080']
